name: Publish to GitHub Packages
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
      steps:
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
      # Publish to GitHub Packages
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}